# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_verssion: [3.5, 3.6, 3.7, 3.8]
    env:
      working-directory: ./phase3_tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lark-parser --upgrade
        python3 cgen_attemp.py
    - name: Install Spim simulator
      run: |
        sudo apt-get update -y
        sudo apt-get install -y spim

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: check directory
      run: ls -l
    - name: implicit fail
      run: throw
      
    - name: Run test script
      run: |
        cd phase3_tests
        chmod +x run.sh
        ./run.sh | tail -n 1 | awk '{print $3}'
